version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  terraform: circleci/terraform@3.0.0

executors:
  terraform:
    docker:
      - image: terraform/default
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

jobs:
  configure-aws:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - run: echo "Run your code here"
  plan-apply:
    executor: terraform
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    executor: terraform
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .
  plan-destroy:
    executor: terraform
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .
  destroy:
    executor: terraform
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy

workflows:
  version: 2
  approve_cycle_orbs:
    jobs:
      - configure-aws
      - terraform/validate:
          checkout: true
          requires:
            - configure-aws
      - terraform/plan:
          checkout: true
          persist-workspace: true
          requires:
            - terraform/validate
      - approve-apply:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          requires:
            - approve-apply
      - approve-destroy:
          type: approval
          requires:
            - terraform/apply
      - terraform/destroy:
          attach-workspace: true
          requires:
            - approve-destroy
  