version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3
  terraform: circleci/terraform@3.0.0

jobs:
  configure-aws:
    executor: aws-cli/default
    steps:
      - aws-cli/setup
      - terraform/install
      - terraform/init
      - terraform/plan

  plan-apply:
    docker:
      - image: terraform/default
    steps:
      - checkout
      - run:
          name: terraform init & plan
          command: |
            terraform init -input=false
            terraform plan -out tfapply -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    docker:
      - image: terraform/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    docker:
      - image: terraform/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            terraform plan -destroy -out tfdestroy -var-file variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: terraform/default
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform apply -auto-approve tfdestroy

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - configure-aws
      - terraform/validate:
          checkout: true
          requires:
            - configure-aws
      - terraform/plan:
          checkout: true
          persist-workspace: true
          requires:
            - terraform/validate
      # - hold-apply:
      #     type: approval
      #     requires:
      #       - plan-apply
      # - apply:
      #     requires:
      #       - hold-apply
      # - plan-destroy:
      #     requires:
      #       - apply
      # - hold-destroy:
      #     type: approval
      #     requires:
      #       - plan-destroy
      # - destroy:
      #     requires:
      #       - hold-destroy
